apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: podinfo
spec:
  type: LoadBalancer     # ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
