###############
## NAMESPACE ##
###############
apiVersion: v1
kind: Namespace
metadata:
  name: hello-test
---
################
## DEPLOYMENT ##
################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-test
  namespace: hello-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-test
  template:
    metadata:
      labels:
        app: hello-test
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.10
        imagePullPolicy: Always
        name: hello-test
        ports:
        - containerPort: 8080
          protocol: TCP
        #resources:
        #  limits:
        #    cpu: 100m
        #    memory: 50Mi
        #  requests:
        #    cpu: 10m
        #    memory: 50Mi
      restartPolicy: Always
      #tolerations:
      #  - key: "kubernetes.azure.com/scalesetpriority"
      #    operator: "Exists"
      #    effect: "NoSchedule"
---
#############
## SERVICE ##
#############
apiVersion: v1
kind: Service
metadata:
  name: hello-test-service
  namespace: hello-test
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-test
  sessionAffinity: None