###############
## NAMESPACE ##
###############
apiVersion: v1
kind: Namespace
metadata:
  name: echo-server
---
################
## DEPLOYMENT ##
################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: echo-server
  #labels:
  #  azure.workload.identity/use: "true"
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
    #  serviceAccountName: workload-identity-sa          # Workload Identity Service Account Name
      containers:
      - name: echo-server
        image: jmalloc/echo-server
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-pod
          protocol: TCP

#        livenessProbe:
#          httpGet:
#            path: /ping
#            port: http-pod        # See value in ports.containerPort
#          failureThreshold: 1
#          periodSeconds: 10

#        startupProbe:
#          httpGet:
#            path: /version
#            port: http-pod        # See value in ports.containerPort
#          failureThreshold: 20
#          periodSeconds: 10
#          initialDelaySeconds: 10

        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
        #    memory: 50Mi
---
#############
## SERVICE ##
#############
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
  namespace: echo-server
spec:
  type: LoadBalancer        # ClusterIP
  selector:
    app: echo-server
  sessionAffinity: None
  ports:
    - name: http-service
      port: 80
      targetPort: 8080
      protocol: TCP

#---
#############
## INGRESS ##
#############
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: echo-server
#  namespace: echo-server
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
#spec:
#  #ingressClassName: nginx
#  tls:
#  - hosts:
#    - ingress-echo-server.dev.internal
#  rules:
#  - host: ingress-echo-server.dev.internal
#    http:
#      paths:
#      - path: /
#        pathType: ImplementationSpecific
#        backend:
#          service:
#            name: echo-server-service
#            port:
#              number: 80
---
####################################
## HPA: Horizontal Pod Autoscaler ##
####################################
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo-server-hpa
  namespace: echo-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  #- type: Pods
  #  pods:
  #    metric:
  #      name: packets-per-second
  #    target:
  #      type: AverageValue
  #      averageValue: 1k
  #- type: Object
  #  object:
  #    metric:
  #      name: requests-per-second
  #    describedObject:
  #      apiVersion: networking.k8s.io/v1
  #      kind: Ingress
  #      name: main-route
  #    target:
  #      type: Value
  #      value: 10k