#############
## SERVICE ##
#############
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
  namespace: echo-server
spec:
  type: LoadBalancer        # ClusterIP
  selector:
    app: echo-server
  sessionAffinity: None
  ports:
    - name: http-service
      port: 80
      targetPort: 8080
      protocol: TCP