apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: argo-apps  # contains application spec files
    repoURL: https://github.com/kramfs/argocd-app-of-apps
    targetRevision: HEAD
    directory:
      recurse: true     # Traverse the directory and apply
  syncPolicy:
    automated:
      prune: true
      selfHeal: true